---
language: python
python: "2.7"

before_install:
  # Make sure everything is up to date
  - sudo apt-get update -qq
  - sudo apt-get install -qq curl libssl-dev

install:
  # Install Ansible
  - pip install ansible

  # Add ansible.cfg to pick up roles path
  - "{ echo '[defaults]'; echo 'roles_path = ../'; echo '[ssh_connection]'; echo 'pipelining=True'; } >> ansible.cfg"

script:
  # Checks to run
  - "ansible-playbook -i tests/inventory tests/test.yml --syntax-check"
  - "ansible-playbook -i tests/inventory tests/test.yml --connection=local --become"
  # - "if [[ -f unrealircd/unfrealircd ]]; then exit 0; else exit 1; fi"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/